export type Property = {
  id: string;
  title: string;
  price: number;
  location: string;
  type: string;
  image_url: string;
  bedrooms: number;
  bathrooms: number;
  area_sqft: number;
  description: string | null;
  created_at: string;
  user_id: string | null;
  detailed_location: string | null;
  town: string | null;
  seller_name: string | null;
  seller_phone: string | null;
  built_year: number | null;
  photos: string[] | null;
  latitude: number | null;
  longitude: number | null;
  status: string;
  seller_id: string | null;
  postal_code: string | null;
  block_number: string | null;
  street_name: string | null;
  hdb_verified: boolean;
  location_verified_at: string | null;
};
